version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/var/lib/mysql
    restart: always
    ports:
      - 27020:27020
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  api_server:
    build: ./api_server
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
  web_server:
    build: ./web_server
    ports:
      - "80:80"
volumes:
  mongo_data: