version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - /data/db:/data/db
    restart: always
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  api_server:
    build: ./api_server
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
    restart: always
    ports:
     - "6379:6379"
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/dist:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf